### ISSUE TITLE
Support https_proxy

### ISSUE THREAD

**Issue by dhoffend** [dlgroep/fetch-crl#1]
The current implimentation doesn't support or honor a https_proxy configuration or environment variable. Since LWP::Useragents needs to have the https proxy configured separately downloads from https websites are not working at all when only http_proxy is set.

Please support https_proxy. If needed I can write a pull request

**Comment by dlgroep** [comment]
Thanks for the report - to clarify the use case a bit further: would it be adequate to use the same proxy endpoint for both `http` and `https`, or are distinct endpoints required? 
The former would make the configuration of fetch-crl slightly simpler.
Happy to implement this one!

**Comment by dlgroep** [comment]
As a short-term workaround, you can set in the `/etc/fetch-crl.conf` file (or in `/etc/fetch-crl.d/`):
```
http_proxy = ENV
```
and then set the environment variables `http_proxy` _and_ `https_proxy`. LWP will then load proxy settings from the *_proxy environment variables.

**Comment by dlgroep** [comment]
Branch https://github.com/dlgroep/fetch-crl/tree/https-proxy-rc adds support for explicitly setting https_proxy, and makes the same (existing) http_proxy setting also apply to https transfers (`https_proxy` can then be used to override this). The setting is mutually exclusive with `http_proxy=ENV` for obvious reasons :)
A preview build and assembled fetch-crl version (3.0.23-RC) is available from https://dl.igtf.net/distribution/tests/PMA-PRIVATE-PREVIEW/fetch-crl3/

**Comment by dhoffend** [comment]
> As a short-term workaround, you can set in the `/etc/fetch-crl.conf` file (or in `/etc/fetch-crl.d/`):
> 
> ```
> http_proxy = ENV
> ```
> 
> and then set the environment variables `http_proxy` _and_ `https_proxy`. LWP will then load proxy settings from the *_proxy environment variables.

In my use case, the webpage I had to download the revocation lists from a server that was https only. I did a similar workaround (setting http_proxy and https_proxy at once). Technically correct would be to configure both seperate (like it must be done in ENV), but for 99% of the use cases, setting both at the same time should be okay. It should be mentioned in the documentation/changelog that both will be set or both can be configures seperate.

**Comment by dhoffend** [comment]
I'm okay with your solution. For more complex configurations the usage of ENV is more suitable. In the beginning I didn't realized the possibilty.

**Comment by dlgroep** [comment]
Thanks for the feed-back. In 3.0.23, the default is now to configure both, but the https_proxy can then additionally be set explicitly (and thereby making it different from http_proxy).
If this branch meets the use case, I'll consolidate and release a new version. In due course, this will end up in oft-used (Linux) package repositories as well (Debian and Fedora EPEL).
